name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
          fetch-depth: 0

      # Say that you want to merge just the actual changes from the PR commits
      # themselves:
      - name: merge changes from turbo key PR zmkfirmware/zmk#1414
        env:
          owner: zmkfirmware
          repo: zmk
          PR: 1414
        run: |
          cd src
          export GIT_COMMITTER_NAME='Github Action' GIT_AUTHOR_NAME='Github Action'
          curl -SsL -o /tmp/${PR}.patch https://github.com/${owner}/${repo}/pull/${PR}.patch
          git apply -3 < /tmp/${PR}.patch
          git commit -m 'Apply changes from ${owner}/${repo} PR#${PR}'

      # Say you want to merge the whole git branch for the PR, including all its history:
      - name: merge branch for BT serial number prefix PR moergosc/zmk#11
        env:
          owner: moergo-sc
          repo: zmk
          PR: 11
        run: |
          cd src
          export GIT_COMMITTER_NAME='Github Action' GIT_AUTHOR_NAME='Github Action'
          git fetch https://github.com/${owner}/${repo} pull/${PR}/head:refs/remotes/upstream/pull/${PR}
          git merge -m "Merge ${owner}/${repo} PR#${PR}" refs/remotes/upstream/pull/${PR}

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: glove80.uf2
          path: glove80.uf2
